# Project
project.version=0.9.23+1.20.1
project.java=17
project.build-java=21
project.minecraft=1.20.1
project.enabled-loaders=forge

# Version Ranges
mod.minecraft-range=[1.20.1, 1.21)
mod.forge-loader-range=[47,)

mixin.compat.common=JAVA_17
mixin.compat.fabric=JAVA_17
mixin.compat.forge=JAVA_17
mixin.compat.neoforge=JAVA_17
