# Project
project.version=0.9.23+1.21.1
project.java=21
project.build-java=21
project.minecraft=1.21.1
project.enabled-loaders=neoforge

# Version Ranges
mod.minecraft-range=[1.21.1, 1.22)
mod.neoforge-loader-range=[1,)

mixin.compat.common=JAVA_21
mixin.compat.fabric=JAVA_21
mixin.compat.forge=JAVA_21
mixin.compat.neoforge=JAVA_21
